"""diamond stock table

Revision ID: 0eea2ee54a7a
Revises: d357da9fe022
Create Date: 2026-03-16 16:45:24.503642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eea2ee54a7a'
down_revision = 'd357da9fe022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diamond_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('clarity', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diamond_stock')
    # ### end Alembic commands ###
