"""production canged

Revision ID: 1fe51bc8f77d
Revises: 9112f088d7a7
Create Date: 2026-03-23 15:06:33.943259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fe51bc8f77d'
down_revision = '9112f088d7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('order_datetime', sa.DateTime(), nullable=False),
    sa.Column('delivery_datetime', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_kyc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('production_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=False),
    sa.Column('diamond_clarity', sa.String(length=20), nullable=True),
    sa.Column('gold_color', sa.String(length=30), nullable=True),
    sa.Column('diamond_color', sa.String(length=20), nullable=True),
    sa.Column('gold_purity', sa.String(length=20), nullable=True),
    sa.Column('gold_purity_factor', sa.Float(), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('style_remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('wax_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('issue_code', sa.String(length=20), nullable=True),
    sa.Column('wax_wt', sa.Float(), nullable=True),
    sa.Column('total_gold_wt', sa.Float(), nullable=True),
    sa.Column('silver_wt', sa.Float(), nullable=True),
    sa.Column('alloy_wt', sa.Float(), nullable=True),
    sa.Column('final_total_wt', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_code')
    )
    op.create_table('wax_issue_gold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('gold_gm', sa.Float(), nullable=True),
    sa.Column('gold_kt', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['wax_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wax_issue_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=True),
    sa.Column('gold_color', sa.String(length=30), nullable=True),
    sa.Column('gold_purity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['wax_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wax_issue_styles')
    op.drop_table('wax_issue_gold')
    op.drop_table('wax_issues')
    op.drop_table('production_status')
    op.drop_table('production_order_items')
    op.drop_table('production_orders')
    # ### end Alembic commands ###
