"""create style_images table

Revision ID: 23acebfa663a
Revises: 76b39c945653
Create Date: 2026-01-26 18:56:23.247370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23acebfa663a'
down_revision = '76b39c945653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_images')
    # ### end Alembic commands ###
