"""add client kyc tables

Revision ID: 28ab8fbdfe31
Revises: 426b89e302b7
Create Date: 2026-03-10 15:10:35.090756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28ab8fbdfe31'
down_revision = '426b89e302b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_kyc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_code', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('company_pan', sa.String(length=20), nullable=True),
    sa.Column('msme_registration', sa.String(length=50), nullable=True),
    sa.Column('iec_code', sa.String(length=30), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('pan_doc', mysql.LONGBLOB(), nullable=True),
    sa.Column('gst_doc', mysql.LONGBLOB(), nullable=True),
    sa.Column('msme_doc', mysql.LONGBLOB(), nullable=True),
    sa.Column('iec_doc', mysql.LONGBLOB(), nullable=True),
    sa.Column('visiting_card_doc', mysql.LONGBLOB(), nullable=True),
    sa.Column('bank_doc', mysql.LONGBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_kyc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_kyc_client_code'), ['client_code'], unique=True)

    op.create_table('client_mou',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('gold_credit_days', sa.Integer(), nullable=True),
    sa.Column('labour_credit_days', sa.Integer(), nullable=True),
    sa.Column('diamond_credit_days', sa.Integer(), nullable=True),
    sa.Column('chain_credit_days', sa.Integer(), nullable=True),
    sa.Column('certificate_hallmark_days', sa.Integer(), nullable=True),
    sa.Column('making_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('chain_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('synthetic_stone_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('minimum_labour_rule', sa.String(length=100), nullable=True),
    sa.Column('nose_pin_labour', sa.String(length=50), nullable=True),
    sa.Column('gold_labour_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mou_document', mysql.LONGBLOB(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_kyc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('aadhar_number', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email_id', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pan_doc', mysql.LONGBLOB(), nullable=True),
    sa.Column('aadhar_doc', mysql.LONGBLOB(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_kyc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('order_datetime', sa.DateTime(), nullable=False),
    sa.Column('delivery_datetime', sa.DateTime(), nullable=True),
    sa.Column('style_no', sa.String(length=100), nullable=False),
    sa.Column('diamond_clarity', sa.String(length=20), nullable=True),
    sa.Column('gold_color', sa.String(length=30), nullable=True),
    sa.Column('diamond_color', sa.String(length=20), nullable=True),
    sa.Column('gold_purity', sa.String(length=20), nullable=True),
    sa.Column('gold_purity_factor', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_kyc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('data', mysql.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_status')
    op.drop_table('production_orders')
    op.drop_table('client_owner')
    op.drop_table('client_mou')
    with op.batch_alter_table('client_kyc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_kyc_client_code'))

    op.drop_table('client_kyc')
    # ### end Alembic commands ###
