"""create client mou table

Revision ID: 426b89e302b7
Revises: a33434e591d9
Create Date: 2026-03-08 11:47:32.272794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '426b89e302b7'
down_revision = 'a33434e591d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_mou',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('gold_credit_days', sa.Integer(), nullable=True),
    sa.Column('labour_credit_days', sa.Integer(), nullable=True),
    sa.Column('diamond_credit_days', sa.Integer(), nullable=True),
    sa.Column('chain_credit_days', sa.Integer(), nullable=True),
    sa.Column('certificate_hallmark_days', sa.Integer(), nullable=True),
    sa.Column('making_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('chain_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('synthetic_stone_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('minimum_labour_rule', sa.String(length=100), nullable=True),
    sa.Column('nose_pin_labour', sa.String(length=50), nullable=True),
    sa.Column('gold_labour_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mou_document', mysql.LONGBLOB(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_kyc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_mou')
    # ### end Alembic commands ###
