"""create image crop table

Revision ID: 4c371569575d
Revises: f33d600d9669
Create Date: 2026-02-22 12:56:47.888178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c371569575d'
down_revision = 'f33d600d9669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_crop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=False),
    sa.Column('image', mysql.LONGBLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_crop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_crop_style_no'), ['style_no'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_crop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_crop_style_no'))

    op.drop_table('image_crop')
    # ### end Alembic commands ###
