"""add client code

Revision ID: 5402c8360bb1
Revises: d6dc22c95562
Create Date: 2026-03-05 14:11:40.265847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5402c8360bb1'
down_revision = 'd6dc22c95562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_kyc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_code', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_client_kyc_client_code'), ['client_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_kyc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_kyc_client_code'))
        batch_op.drop_column('client_code')

    # ### end Alembic commands ###
