"""add sieve and diamond fields to style_images

Revision ID: 547e03bb5ae3
Revises: 5c4fb4462efe
Create Date: 2026-01-29 14:47:03.878607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '547e03bb5ae3'
down_revision = '5c4fb4462efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sieve_range', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sieve_size', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mm_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('no_of_stones', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ct_weight_per_piece', sa.Float(), nullable=True))
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
        batch_op.drop_column('ct_weight_per_piece')
        batch_op.drop_column('no_of_stones')
        batch_op.drop_column('mm_size')
        batch_op.drop_column('sieve_size')
        batch_op.drop_column('sieve_range')

    # ### end Alembic commands ###
