"""drop wax_issues table1

Revision ID: 589d8de46a34
Revises: 60a7f1ada5d9
Create Date: 2026-03-23 11:36:48.968980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589d8de46a34'
down_revision = '60a7f1ada5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wax_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('issue_code', sa.String(length=20), nullable=True),
    sa.Column('wax_wt', sa.Float(), nullable=True),
    sa.Column('total_gold_wt', sa.Float(), nullable=True),
    sa.Column('silver_wt', sa.Float(), nullable=True),
    sa.Column('alloy_wt', sa.Float(), nullable=True),
    sa.Column('final_total_wt', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_code')
    )
    op.create_table('wax_issue_gold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('gold_gm', sa.Float(), nullable=True),
    sa.Column('gold_kt', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['wax_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wax_issue_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=True),
    sa.Column('gold_color', sa.String(length=30), nullable=True),
    sa.Column('gold_purity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['wax_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wax_issue_styles')
    op.drop_table('wax_issue_gold')
    op.drop_table('wax_issues')
    # ### end Alembic commands ###
