"""diamond issue

Revision ID: 592390ffb6f7
Revises: 67f090f6b671
Create Date: 2026-03-29 14:48:50.207219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592390ffb6f7'
down_revision = '67f090f6b671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diamond_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_code', sa.String(length=20), nullable=True),
    sa.Column('total_pcs', sa.Integer(), nullable=True),
    sa.Column('total_ct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_code')
    )
    op.create_table('diamond_issue_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('pcs', sa.Integer(), nullable=True),
    sa.Column('ct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['diamond_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diamond_issue_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=True),
    sa.Column('clarity', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('pcs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['diamond_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diamond_issue_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['diamond_issues.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diamond_issue_orders')
    op.drop_table('diamond_issue_styles')
    op.drop_table('diamond_issue_rounds')
    op.drop_table('diamond_issues')
    # ### end Alembic commands ###
