"""create style_images with longblob

Revision ID: 5c4fb4462efe
Revises: e84da1f97581
Create Date: 2026-01-27 11:52:00.679516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c4fb4462efe'
down_revision = 'e84da1f97581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=False),
    sa.Column('image', mysql.LONGBLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_images_style_no'), ['style_no'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_images_style_no'))

    op.drop_table('style_images')
    # ### end Alembic commands ###
