"""change blob to longblob for documents

Revision ID: 76b39c945653
Revises: 7fed7fc55557
Create Date: 2026-01-25 22:13:43.605939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76b39c945653'
down_revision = '7fed7fc55557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_kyc', schema=None) as batch_op:
        batch_op.alter_column('aadhar_doc',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('gst_doc',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('pan_doc',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('msme_doc',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('iec_doc',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('visiting_card_doc',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_kyc', schema=None) as batch_op:
        batch_op.alter_column('visiting_card_doc',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('iec_doc',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('msme_doc',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('pan_doc',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('gst_doc',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('aadhar_doc',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
