"""create gold stock

Revision ID: 7a32faf1e90c
Revises: d73fb1af28fd
Create Date: 2026-03-20 22:06:59.001773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a32faf1e90c'
down_revision = 'd73fb1af28fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_type', sa.String(length=20), nullable=False),
    sa.Column('gold_type', sa.String(length=30), nullable=True),
    sa.Column('purity', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('silver_weight', sa.Float(), nullable=True),
    sa.Column('alloy_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wax_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('issue_code', sa.String(length=20), nullable=True),
    sa.Column('wax_wt', sa.Float(), nullable=True),
    sa.Column('total_gold_wt', sa.Float(), nullable=True),
    sa.Column('silver_wt', sa.Float(), nullable=True),
    sa.Column('alloy_wt', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_code')
    )
    op.create_table('wax_issue_gold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('gold_gm', sa.Float(), nullable=True),
    sa.Column('gold_kt', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['wax_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wax_issue_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=True),
    sa.Column('gold_color', sa.String(length=30), nullable=True),
    sa.Column('gold_purity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['wax_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wax_issue_styles')
    op.drop_table('wax_issue_gold')
    op.drop_table('wax_issues')
    op.drop_table('gold_stock')
    # ### end Alembic commands ###
