"""create client_kyc table

Revision ID: 7fed7fc55557
Revises: 
Create Date: 2026-01-25 20:02:29.376058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fed7fc55557'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_kyc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('alt_phone', sa.String(length=20), nullable=True),
    sa.Column('office_phone', sa.String(length=20), nullable=True),
    sa.Column('landline', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('company_pan', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('aadhar_number', sa.String(length=20), nullable=True),
    sa.Column('msme_registration', sa.String(length=50), nullable=True),
    sa.Column('diamond_weight_lazer_marking', sa.String(length=50), nullable=True),
    sa.Column('iec_code', sa.String(length=30), nullable=True),
    sa.Column('aadhar_doc', sa.LargeBinary(), nullable=True),
    sa.Column('gst_doc', sa.LargeBinary(), nullable=True),
    sa.Column('pan_doc', sa.LargeBinary(), nullable=True),
    sa.Column('msme_doc', sa.LargeBinary(), nullable=True),
    sa.Column('iec_doc', sa.LargeBinary(), nullable=True),
    sa.Column('visiting_card_doc', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_kyc')
    # ### end Alembic commands ###
