"""production table changed

Revision ID: 9112f088d7a7
Revises: 49a814efafa6
Create Date: 2026-03-23 14:48:33.722255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9112f088d7a7'
down_revision = '49a814efafa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_no',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=False),
    sa.Column('gold_wt', sa.Float(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('pcs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_no', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_no_style_no'), ['style_no'], unique=False)

    op.create_table('production_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=False),
    sa.Column('diamond_clarity', sa.String(length=20), nullable=True),
    sa.Column('gold_color', sa.String(length=30), nullable=True),
    sa.Column('diamond_color', sa.String(length=20), nullable=True),
    sa.Column('gold_purity', sa.String(length=20), nullable=True),
    sa.Column('gold_purity_factor', sa.Float(), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('style_remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_order_items')
    with op.batch_alter_table('style_no', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_no_style_no'))

    op.drop_table('style_no')
    # ### end Alembic commands ###
