"""Added bank doc to ClientKYC

Revision ID: a33434e591d9
Revises: da6956ddbab7
Create Date: 2026-03-06 21:10:49.572465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a33434e591d9'
down_revision = 'da6956ddbab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_kyc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_doc', mysql.LONGBLOB(), nullable=True))
        batch_op.drop_column('diamond_weight_lazer_marking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_kyc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diamond_weight_lazer_marking', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('bank_doc')

    # ### end Alembic commands ###
