"""create style_images

Revision ID: a3dba5ae580c
Revises: c7f7d9f9cd58
Create Date: 2026-01-27 11:45:15.651917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3dba5ae580c'
down_revision = 'c7f7d9f9cd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_style_images_style_no'), ['style_no'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_images_style_no'))
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               nullable=True)

    # ### end Alembic commands ###
