"""add gold wt gem count round details

Revision ID: ac3fbcd399aa
Revises: dd2f34a227a4
Create Date: 2026-02-03 10:55:38.052823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac3fbcd399aa'
down_revision = 'dd2f34a227a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold_wt', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_gem_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('round_details', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.drop_column('round_details')
        batch_op.drop_column('total_gem_count')
        batch_op.drop_column('gold_wt')

    # ### end Alembic commands ###
