"""change image column to LargeBinary

Revision ID: c7f7d9f9cd58
Revises: 23acebfa663a
Create Date: 2026-01-27 10:47:31.718721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7f7d9f9cd58'
down_revision = '23acebfa663a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.alter_column('style_no',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=mysql.TEXT(),
               type_=sa.LargeBinary(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('style_no',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
