"""gold stock table

Revision ID: d357da9fe022
Revises: f79383a1b721
Create Date: 2026-03-16 10:26:09.501174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd357da9fe022'
down_revision = 'f79383a1b721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gold_type', sa.String(length=20), nullable=True),
    sa.Column('purity', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gold_stock')
    # ### end Alembic commands ###
