"""add unique constraint to wax_issue_styles

Revision ID: da2896b6853b
Revises: 4e4f7dcb7592
Create Date: 2026-04-23 14:13:47.305719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2896b6853b'
down_revision = '4e4f7dcb7592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_order_style'))

    with op.batch_alter_table('wax_issue_styles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'production_orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wax_issue_styles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('production_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_order_style'), ['order_id', 'style_no'], unique=True)

    # ### end Alembic commands ###
