"""Added bank details to ClientKYC

Revision ID: da6956ddbab7
Revises: 5402c8360bb1
Create Date: 2026-03-06 15:59:23.641527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6956ddbab7'
down_revision = '5402c8360bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_kyc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_kyc', schema=None) as batch_op:
        batch_op.drop_column('branch')
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
