"""add gold and diamond weight

Revision ID: dd2f34a227a4
Revises: 547e03bb5ae3
Create Date: 2026-01-29 15:37:44.348019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd2f34a227a4'
down_revision = '547e03bb5ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diamond_sieve_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sieve_range', sa.String(length=50), nullable=False),
    sa.Column('sieve_size', sa.String(length=20), nullable=False),
    sa.Column('mm_size', sa.Float(), nullable=False),
    sa.Column('no_of_stones', sa.Integer(), nullable=False),
    sa.Column('ct_weight_per_piece', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)
        batch_op.drop_column('ct_weight_per_piece')
        batch_op.drop_column('sieve_size')
        batch_op.drop_column('sieve_range')
        batch_op.drop_column('no_of_stones')
        batch_op.drop_column('mm_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mm_size', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('no_of_stones', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sieve_range', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sieve_size', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('ct_weight_per_piece', mysql.FLOAT(), nullable=True))
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=False)

    op.drop_table('diamond_sieve_master')
    # ### end Alembic commands ###
