"""add production_orders

Revision ID: e647a0ee98c2
Revises: ac3fbcd399aa
Create Date: 2026-02-10 17:31:48.432733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e647a0ee98c2'
down_revision = 'ac3fbcd399aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('order_datetime', sa.DateTime(), nullable=False),
    sa.Column('delivery_datetime', sa.DateTime(), nullable=True),
    sa.Column('style_no', sa.String(length=100), nullable=False),
    sa.Column('gross_weight_gm', sa.Float(), nullable=True),
    sa.Column('total_diamond_pcs', sa.Integer(), nullable=True),
    sa.Column('total_diamond_ct', sa.Float(), nullable=True),
    sa.Column('net_weight_gm', sa.Float(), nullable=True),
    sa.Column('diamond_clarity', sa.String(length=20), nullable=True),
    sa.Column('diamond_color', sa.String(length=20), nullable=True),
    sa.Column('gold_color', sa.String(length=30), nullable=True),
    sa.Column('gold_purity', sa.String(length=20), nullable=True),
    sa.Column('gold_purity_factor', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_orders')
    # ### end Alembic commands ###
