"""init

Revision ID: f33d600d9669
Revises: 
Create Date: 2026-02-21 23:51:23.903075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33d600d9669'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_no',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_no', sa.String(length=100), nullable=False),
    sa.Column('gold_wt', sa.Float(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('pcs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_no', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_no_style_no'), ['style_no'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_no', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_no_style_no'))

    op.drop_table('style_no')
    # ### end Alembic commands ###
